name: 'prepare-k8s-env'
description: 'preparing a k8s cluster'
inputs:
  k8s-host-url:
    description: "api url to a k8s cluster"
    required: true
  k8s-token:
    description: "k8s account token"
    required: true
  k8s-cluster-name:
    description: "k8s cluster name"
    required: true
    default: "cluster-${GITHUB_RUN_NUMBER}"
  k8s-user-name:
    description: "k8s user name"
    required: true
    default: "user-${GITHUB_RUN_NUMBER}"
  kubectl-version:
    description: "kubectl version"
    required: true
    default: "latest"
  helm-version:
    description: "helm version"
    required: true
    default: "3.14.0"

runs:
  using: "composite"
  steps:
  - uses: azure/setup-kubectl@v3
    with:
      version: ${{ inputs.kubectl-version}}
  - uses: azure/setup-helm@v3
    with:
      version: ${{ inputs.helm-version }}
  - name: login to k8s cluster
    env:
      K8S_HOST_URL: ${{ inputs.k8s-host-url }}
      K8S_TOKEN: ${{ inputs.k8s-token }}
      K8S_CLUSTER_NAME: ${{ inputs.k8s-cluster-name }}
      K8S_USER_NAME: ${{ inputs.k8s-user-name }}
    run: |
      kubectl config set-cluster "${K8S_CLUSTER_NAME}" --server="${K8S_HOST_URL}" --insecure-skip-tls-verify=true
      kubectl config set-credentials "${K8S_USER_NAME}" --token="${K8S_TOKEN}"
      kubectl config set-context "${K8S_CLUSTER_NAME}" --cluster="${K8S_CLUSTER_NAME}" --user="${K8S_USER_NAME}"
      kubectl config use-context "${K8S_CLUSTER_NAME}"
    shell: bash